name: Bug Report
description: Report an Issue or Bug with the Telemetry Package
labels: [ "bug" ]

body:
    -   type: markdown
        attributes:
            value: |
                We're sorry to hear you have a problem. Can you help us solve it by providing the following details.
    -   type: textarea
        id: what-happened
        attributes:
            label: What Happened
            description: What did you expect to happen?
        validations:
            required: true
    -   type: textarea
        id: how-to-reproduce
        attributes:
            label: How to Reproduce
            description: How did this occur, please add any config values used and provide a set of reliable steps if possible.
            placeholder: Install a fresh app, attach Requests middleware, ...
        validations:
            required: true
    -   type: input
        id: feed-version
        attributes:
            label: Telemetry Version
            description: What version of our Package are you running? Please be as specific as possible
            placeholder: 1.0.0
        validations:
            required: true
    -   type: input
        id: php-version
        attributes:
            label: PHP Version
            description: What version of PHP are you running? Please be as specific as possible
            placeholder: 8.4.12
        validations:
            required: true
    -   type: dropdown
        id: operating-systems
        attributes:
            label: Operation System
            description: On which operating systems does the problem occur? You can select more than one.
            multiple: true
            options:
                - macOS
                - Windows
                - Linux
        validations:
            required: true
    -   type: textarea
        id: notes
        attributes:
            label: Notes
            description: Use this field to provide any other notes that you feel might be relevant to the issue.
        validations:
            required: false

    -   type: markdown
        attributes:
            value: |
                ❤️ The Dragon Code? Please consider supporting [`our collective`](https://boosty.to/dragon-code).
